mongo_data:
  image: busybox
  volumes:
    - /data/db
mongo:
  image: docker.123-dev.co.uk/cop/mongo:latest
  volumes_from:
    - mongo_data
  ports:
    - 27017:27017
cop-backend-api:
  image: docker.123-dev.co.uk/cop/nodejs:latest
  ports:
    - 3000:3000 # development
    - 9000:9000 # test
    - 8080:8080 # production
  environment:
    NODE_ENV: development
    #NODE_ENV: Production
    #NODE_ENV: Test
  links:
    - mongo
